POST http://localhost:8080/customers
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice@example.com"
}

###

POST http://localhost:8080/orders
Content-Type: application/json

{
  "status": "NEW",
  "customerId": 1
}