apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: adishadush/order-management:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-management-secret
                  key: JWT_SECRET

            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: order-management-secret
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-management-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-management-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"